### ISSUE TITLE
Allow a given unit to be mapped to more than one other unit during merge conflict

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#156]
For example, substance_per_volume ends up mapping to both millimolar and micromolar in the Jiang+Pedersen (CellML+SBML) merge task, but SG only considers one of these mappings (right Chris?).

**Comment by thompsct** [comment]
Right

**Comment by thompsct** [comment]
It turns out the conflict resolver doesn't use a map and should work correctly. There may be another problem though. When the Biosim model is merged with the Pedersen model and the Biosim model is chosen for all three overlaps, multiple parts of the Pedersen model are removed (including one of the overlaps and all of its connections, Gi.Gi).

**Comment by thompsct** [comment]
The master branch gives the same results.

**Comment by maxneal** [comment]
Chris - two things.

1) It doesn't look like the Stage Merger is applying unit correction factors at all in the resulting merged code. So I can't test whether this units mapping issue really exists. Can you look into why the unit conversion factors aren't getting written out? If you want a simple test, you can try the CardiovascularDynamics + Baroreceptor merge. Then enter some conversion factor for the one unit conflict that shows up, and then save out to a .proj file. The conversion factor should show up in the resulting MML code (it does when I use the old merger), but it doesn't.

2) When you say Biosim model you mean the Jiang model from BioModels?  If so, then I think the reason parts of the Pedersen model are being removed is because SG prunes out the "dead" portions of component models during the merge. Only preserving terms from Jiang probably results in some of these dead ends on the Pedersen side.

**Comment by thompsct** [comment]
Which two versions are you using? The annotated models in Dropbox produce an error when I attempt to merge them.

**Comment by maxneal** [comment]
Sorry - I should have mentioned I just pushed a fix for that error in the Stage Merger branch. If you pull in the change, the models on DropBox should work.

**Comment by thompsct** [comment]
I see what you mean. I'm looking into it.

**Comment by thompsct** [comment]
Alright, there were actually two issues. In the first, name changes were not getting added to the map in Merger/MergerTask resulting in the merger failing to replace the discarded codeword. Second, when the second representation was made, the operator was not being flipped. Both problems are fixed.

**Comment by maxneal** [comment]
Thanks Chris. When I tried out the CV+BARO merge and entered 1234 as the conversion factor for min^-1 : 1/min, then attempted to save the merge as a .proj file, SG throws the following exception:

java.lang.UnsupportedOperationException
	at org.apache.commons.lang3.tuple.ImmutablePair.setValue(ImmutablePair.java:101)
	at semgen.merging.workbench.Merger.merge(Merger.java:103)
	at semgen.merging.workbench.MergerTask.doInBackground(MergerTask.java:48)
	at semgen.merging.workbench.MergerTask.doInBackground(MergerTask.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at semgen.utilities.file.SemGenSaveFileChooser.SaveAsAction(SemGenSaveFileChooser.java:138)
	at semgen.merging.workbench.MergerWorkbench.saveModelAs(MergerWorkbench.java:369)
	at semgen.stage.stagetasks.merge.MergerTask.saveMerge(MergerTask.java:160)
	at semgen.stage.stagetasks.merge.MergerTask.update(MergerTask.java:173)
	at java.util.Observable.notifyObservers(Unknown Source)
	at semgen.merging.workbench.MergerWorkbench$1.endTask(MergerWorkbench.java:326)
	at semgen.utilities.SemGenTask.done(SemGenTask.java:31)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by thompsct** [comment]
It looks like you have to save it in an existing project file. Is SemGen setup to create a new project file if the one specified doesn't exist?

**Comment by maxneal** [comment]
Yes, you can save to either a new proj or an existing proj. But I don't think that's the issue. I get the exception whether or not I save to an existing proj.

**Comment by maxneal** [comment]
I no longer get the exception, but SG isn't rewriting the equations correctly when introducing unit correction factors. For example, the equation for EDVLV:t in the CV+BARO merge turns into

	EDVLV:t =0) or (sin((t-PRint)*(HR/1234.0)*.10471975511965977)>0)) and (sin((t-PRint-t.t.delta)*(HR/1234.0)*.10471975511965977)<0)){ EDVLV = VLV; }

The right hand side of the equation is missing the first part. Here's the original equation:

EDVLV:t = event(((sin((t-PRint)*HR*.10471975511965977)=0) or (sin((t-PRint)*HR*.10471975511965977)>0)) and (sin((t-PRint-t.delta)*HR*.10471975511965977)<0)){ EDVLV = VLV; }

**Comment by thompsct** [comment]
Looking into this, it looks like every instance of the codeword is getting replaced with the conversion factor.

**Comment by maxneal** [comment]
The issue is with the MMLwriter. It's not dealing with so-called "realState" variables in JSim models correctly when writing them out. I should be able to fix it.

**Comment by maxneal** [comment]
OK I think these issues with the CV+BARO merged were fixed in commit #e168e50.  Returning to the original issue here, the multiple units mapping for the Jiang+Pedersen merge.

**Comment by maxneal** [comment]
The units mapping appears to be working correctly when tested out on the Jiang+Pedersen merge.
